version: "3"
services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: backend
    command: >
      bash -c "uvicorn app:app --host 0.0.0.0 --port 8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: backend
    command: >
      bash -c "npm run build"
    volumes:
      - frontend_volume:/app/build

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./.docker/nginx/
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend_volume:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"



volumes:
  frontend_volume: